/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChaoProgressBar {
        "progress": number;
    }
}
declare global {
    interface HTMLChaoProgressBarElement extends Components.ChaoProgressBar, HTMLStencilElement {
    }
    var HTMLChaoProgressBarElement: {
        prototype: HTMLChaoProgressBarElement;
        new (): HTMLChaoProgressBarElement;
    };
    interface HTMLElementTagNameMap {
        "chao-progress-bar": HTMLChaoProgressBarElement;
    }
}
declare namespace LocalJSX {
    interface ChaoProgressBar {
        "progress"?: number;
    }
    interface IntrinsicElements {
        "chao-progress-bar": ChaoProgressBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chao-progress-bar": LocalJSX.ChaoProgressBar & JSXBase.HTMLAttributes<HTMLChaoProgressBarElement>;
        }
    }
}
